### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by Wrosh** [PHR16384/PHRhome#1]
thanks for consolas font brother i really like it. I hope good old lucas de groot wont hate us after this! yo ho ho ho!

**Comment by PHR16384** [comment]
> thanks for consolas font brother i really like it. I hope good old lucas de groot wont hate us after this! yo ho ho ho!

You're welcome!  Though if memory serves, Consolas is a proprietary font (included with Windows), from however long ago it's been since I touched this repo.

In 2024 I'd recommend FOSS alternatives like [Hack](https://sourcefoundry.org/hack/).
